# Generated by Django 6.0 on 2025-12-31 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearnBuddy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
